---
# Project Information
site_name: Roughness
site_url: https://nau-pixel.github.io/roughness
site_author: Christian Tai Udovicic
site_description: Documentation for the roughness python package.

# Repository information
repo_name: NAU-PIXEL/roughness
repo_url: https://github.com/NAU-PIXEL/roughness
edit_uri: "edit/main/docs/"

# Copyright
copyright: Copyright &copy; 2023 Christian Tai Udovicic

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    view: material/eye
  features:
    - navigation.instant
    - navigation.tabs
  language: en

plugins:
  - search
  - gen-files:
      scripts:
      - docs/gen_api_pages.py
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [roughness]
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocs-jupyter:
      include_source: true
      execute: true
      allow_errors: false

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nau-pixel
      name: NAU-PIXEL on GitHub

# Page tree
nav:
  - Home: index.md
  - 'User Guide':
    - 'Getting Started': 'getting_started.md'
    - 'Shadow Tables': 'shadow_tables.ipynb'
    - 'Rough emission': 'rough_emission.ipynb'
  - About: about.md
  - Code Reference: reference/

not_in_nav: |
  gen_api_pages.py

# Enable math (req. python-markdown-math)
extra_javascript:
  - docs/javascript/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
