---
# Project Information
site_name: roughness
site_author: Christian Tai Udovicic
site_description: Predict surface illumination accounting for roughness

# Repository information
repo_name: cjtu/roughness
repo_url: https://github.com/cjtu/roughness
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 Christian Tai Udovicic

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: en

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cjtu
      name: cjtu on GitHub

# Page tree
nav:
  - Home: index.md
