---
# Project Information
site_name: roughness
site_author: Christian Tai Udovicic
site_description: Predict surface illumination accounting for roughness

# Repository information
repo_name: NAU-PIXEL/roughness
repo_url: https://github.com/NAU-PIXEL/roughness
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 Christian Tai Udovicic

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: en

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nau-pixel
      name: NAU-PIXEL on GitHub

# Page tree
nav:
  - Home: index.md

# Enable math (req. python-markdown-math)
extra_javascript:
  - javascript/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
