---
name: Code Quality Checks

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      - name: Activate venv
        run: source .venv/bin/activate
      - name: Unit & Coverage test with pytest
        run: poetry run pytest
      - name: Check style with pylint
        run: poetry run pylint roughness/ tests/
      - name: Check format with black
        run: poetry run black --check roughness/ tests/
      # - name: Check type hinting with mypy
      #   run: poetry run mypy --strict --config-file=mypy.ini roughness/
      
